services:
  backend:
    container_name: sendme_backend
    build:
      context: ./sendme_back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./sendme_back:/app
      - /app/target
    depends_on:
      - db

  frontend:
    container_name: sendme_frontend
    build:
      context: ./sendme_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./sendme_front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    container_name: sendme_db
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: