services:
  sendme_front:
    image: node:20-alpine
    container_name: sendme_front
    restart: unless-stopped
    volumes:
      - ./sendme_front2:/app
      - /app/node_modules
      - /app/build
      - /app/.next
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: "/app"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - sendme_back

  sendme_back:
    container_name: sendme_back
    build: ./sendme_back
    volumes:
      - ./sendme_back:/app
      - /home/gradle/.gradle
    ports:
      - "8000:8000"
      - "5005:5005"
    user: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    working_dir: "/app"
    command: >
      sh -c "if [ ! -f ./gradlew ]; then gradlew wrapper; fi && ./gradlew build --no-daemon && ./gradlew bootRun --continuous"
    depends_on:
      - sendme_db

  sendme_db:
    image: postgres:latest
    container_name: sendme_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sendme
      POSTGRES_PASSWORD: 9Oe9oaDjcX5RLeX
      POSTGRES_DB: sendme_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"