services:
  sendme_front:
    image: node:22-alpine
    container_name: sendme_front
    volumes:
      - ./sendme_front:/app
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    restart: always
    working_dir: "/app"
    command: >
      sh -c "npm i && npm run build && npm run watch"
    links:
      - sendme_back
    depends_on:
      - sendme_back
  sendme_back:
    image: eclipse-temurin:23-jdk
    container_name: sendme_back
    volumes:
      - ./sendme_back:/app
      - ~/.gradle:/home/gradle/.gradle
    ports:
      - "8000:8000"
      - "5005:5005"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n
    working_dir: "/app"
    command: > 
      sh -c "./gradlew build --daemon && ./gradlew bootRun --continuous"
    links:
      - sendme_db
    depends_on:
      - sendme_db
  sendme_db:
    image: postgres:latest
    container_name: sendme_db
    environment:
      POSTGRES_USER: sendme
      POSTGRES_PASSWORD: 9Oe9oaDjcX5RLeX
      POSTGRES_DB: sendme_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"